### ISSUE TITLE
Prisma-level 

### ISSUE THREAD

**Issue by joselvelez** [prisma/docs#4822]
/In reading the docs regarding many-to-many relations for MongoDB at [MongoDB m-n relations
](https://www.prisma.io/docs/concepts/components/prisma-schema/relations)

Something is not very clear to me for the below many-to-many example: Would it help to add some additional detail on whether the `categoryIDs[ ]` and `postIDs[ ]` relations are considered prisma-level relation fields?

```prisma
model Post {
  id          String     @id @default(auto()) @map("_id") @db.ObjectId
  categoryIDs String[]   @db.ObjectId
  categories  Category[] @relation(fields: [categoryIDs], references: [id])
}

model Category {
  id      String   @id @default(auto()) @map("_id") @db.ObjectId
  name    String
  postIDs String[] @db.ObjectId
  posts   Post[]   @relation(fields: [postIDs], references: [id])
}
``` 
The below example given in the docs is for a one-to-many relation. 

```
model User {
  id    String @id @default(auto()) @map("_id") @db.ObjectId
  posts Post[]
}

model Post {
  id       String @id @default(auto()) @map("_id") @db.ObjectId
  author   User   @relation(fields: [authorId], references: [id])
  authorId String @db.ObjectId // relation scalar field  (used in the `@relation` attribute above)
}
```

The documention states:

> Two [relation fields](https://www.prisma.io/docs/concepts/components/prisma-schema/relations#relation-fields): author and posts. Relation fields define connections between models at the Prisma level and do not exist in the database. These fields are used to generate Prisma Client.

**Comment by janpio** [comment]
`categories` and `posts` are relation fields. `categoryIDs` and `postIDs` are lists of relation scalars (equivalent to `authorId` in the second example - they are just on both sides because of the way we decided to represent relations in MongoDB.)

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
